CC=gcc
CFLAGS=-Wall -g

all: run

161044085_sehmus_acar_HW1: 161044085_sehmus_acar_HW1.c
	$(CC) $(CFLAGS) -o 161044085_sehmus_acar_HW1 161044085_sehmus_acar_HW1.c

run: 161044085_sehmus_acar_HW1
	./161044085_sehmus_acar_HW1

clean:
	rm -f 161044085_sehmus_acar_HW1 *.o log.txt *.txt
